---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'afterclass2'
    - 'md/division-project'
    - '$default'
