---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'afterclass'
    - 'md/division-project'
    - '$default'
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.socialCalendarCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "socialCalendarCache"